### ISSUE TITLE
The file 'NeptuneC_MD_VC141.dll' is missing from the project.

### ISSUE THREAD

**Issue by jaesuphwang** [thanhhung0112/Template-Matching#1]
Hi there!
I am interested in your work and have tried to build & run your codebase.
However, the file, 'NeptuneC_MD_VC141.dll', is missing from your project.
Please let me know how to get it.

Thanks.
Best regards.

**Comment by thanhhung0112** [comment]
Thank you for taking an interest in my repo. 
You access to this link [IMI_TECH](http://www.imi-tech.com/en/sub02_05.php?fbclid=IwAR2LUch8XKFJWTXENYJjUB5CC8byv8KJeULzeXNET2zQwrGVJs7M8n4VBZ0#soft01), and download the GigE USB 3.0 interface, then just install it.

**Comment by jaesuphwang** [comment]
Thank you for your quick response.

I have downloaded the file and installed it.

 

 

Thanks.

Best regards.
